# Copyright (c) 2026 Atakan DULKER. Licensed under the MIT License.
#
# Read the Core-owned preparation report written by Tools/prepare-core.sh.
#
# Core checkout discovery, SwiftPM preparation, and contract validation belong
# to the Core tool. This file only translates the versioned report into the
# CMake variables used by the ESP-IDF components. It never searches a parent
# directory and never reads a Core build directory.

if(AXOLOTY_PREPARATION_REPORT_LOADED)
    return()
endif()
set(AXOLOTY_PREPARATION_REPORT_LOADED TRUE)

if(NOT DEFINED AXOLOTY_PREPARATION_REPORT OR
   "${AXOLOTY_PREPARATION_REPORT}" STREQUAL "")
    if(DEFINED ENV{AXOLOTY_PREPARATION_REPORT})
        set(AXOLOTY_PREPARATION_REPORT "$ENV{AXOLOTY_PREPARATION_REPORT}")
    endif()
endif()

if(NOT DEFINED AXOLOTY_PREPARATION_REPORT OR
   "${AXOLOTY_PREPARATION_REPORT}" STREQUAL "")
    message(FATAL_ERROR
        "AXOLOTY_PREPARATION_REPORT is required; run Tools/prepare-core.sh first"
    )
endif()

if(NOT IS_ABSOLUTE "${AXOLOTY_PREPARATION_REPORT}" OR
   NOT EXISTS "${AXOLOTY_PREPARATION_REPORT}")
    message(FATAL_ERROR
        "AXOLOTY_PREPARATION_REPORT must be an existing absolute file: ${AXOLOTY_PREPARATION_REPORT}"
    )
endif()
file(REAL_PATH "${AXOLOTY_PREPARATION_REPORT}" AXOLOTY_PREPARATION_REPORT_REAL)
if(NOT "${AXOLOTY_PREPARATION_REPORT}" STREQUAL "${AXOLOTY_PREPARATION_REPORT_REAL}")
    message(FATAL_ERROR "AXOLOTY_PREPARATION_REPORT must be canonical")
endif()
file(READ "${AXOLOTY_PREPARATION_REPORT}" AXOLOTY_PREPARATION_JSON)

string(JSON AXOLOTY_PREPARATION_SCHEMA GET "${AXOLOTY_PREPARATION_JSON}" schemaVersion)
if(NOT AXOLOTY_PREPARATION_SCHEMA EQUAL 1)
    message(FATAL_ERROR "unsupported Core preparation schema: ${AXOLOTY_PREPARATION_SCHEMA}")
endif()
string(JSON AXOLOTY_PREPARATION_STATUS GET "${AXOLOTY_PREPARATION_JSON}" status)
if(NOT AXOLOTY_PREPARATION_STATUS STREQUAL "prepared")
    message(FATAL_ERROR "Core preparation did not pass: ${AXOLOTY_PREPARATION_STATUS}")
endif()

string(JSON AXOLOTY_SOURCE_DIR GET "${AXOLOTY_PREPARATION_JSON}" core sourceDir)
string(JSON AXOLOTY_CORE_SHA GET "${AXOLOTY_PREPARATION_JSON}" core sha)
string(JSON AXOLOTY_CORE_DIRTY_VALUE GET "${AXOLOTY_PREPARATION_JSON}" core dirty)
if(NOT IS_ABSOLUTE "${AXOLOTY_SOURCE_DIR}" OR NOT IS_DIRECTORY "${AXOLOTY_SOURCE_DIR}")
    message(FATAL_ERROR "Core sourceDir in the preparation report is not a directory")
endif()
file(REAL_PATH "${AXOLOTY_SOURCE_DIR}" AXOLOTY_SOURCE_DIR_REAL)
if(NOT "${AXOLOTY_SOURCE_DIR}" STREQUAL "${AXOLOTY_SOURCE_DIR_REAL}")
    message(FATAL_ERROR "Core sourceDir in the preparation report must be canonical")
endif()
string(LENGTH "${AXOLOTY_CORE_SHA}" AXOLOTY_CORE_SHA_LENGTH)
if(NOT AXOLOTY_CORE_SHA_LENGTH EQUAL 40 OR
   NOT AXOLOTY_CORE_SHA MATCHES "^[0-9a-fA-F]+$")
    message(FATAL_ERROR "Core sha in the preparation report is invalid")
endif()
if(AXOLOTY_CORE_DIRTY_VALUE STREQUAL "true" OR
   AXOLOTY_CORE_DIRTY_VALUE STREQUAL "ON" OR
   AXOLOTY_CORE_DIRTY_VALUE STREQUAL "1")
    set(AXOLOTY_CORE_DIRTY 1)
else()
    set(AXOLOTY_CORE_DIRTY 0)
endif()

# A caller may select the Core checkout in the environment. The report remains
# authoritative, but this check catches a stale or mismatched environment
# before CMake starts compiling firmware.
if(DEFINED ENV{AXOLOTY_SOURCE_DIR} AND NOT "$ENV{AXOLOTY_SOURCE_DIR}" STREQUAL "")
    file(REAL_PATH "$ENV{AXOLOTY_SOURCE_DIR}" AXOLOTY_SELECTED_SOURCE_DIR)
    if(NOT "${AXOLOTY_SELECTED_SOURCE_DIR}" STREQUAL "${AXOLOTY_SOURCE_DIR}")
        message(FATAL_ERROR "AXOLOTY_SOURCE_DIR disagrees with the preparation report")
    endif()
endif()

string(JSON AXOLOTY_PACKAGE_COUNT LENGTH "${AXOLOTY_PREPARATION_JSON}" portablePackages)
math(EXPR AXOLOTY_PACKAGE_LAST "${AXOLOTY_PACKAGE_COUNT} - 1")
foreach(AXOLOTY_PACKAGE_INDEX RANGE ${AXOLOTY_PACKAGE_LAST})
    string(JSON AXOLOTY_PACKAGE_NAME GET
        "${AXOLOTY_PREPARATION_JSON}" portablePackages ${AXOLOTY_PACKAGE_INDEX} name
    )
    string(JSON AXOLOTY_PACKAGE_SOURCE GET
        "${AXOLOTY_PREPARATION_JSON}" portablePackages ${AXOLOTY_PACKAGE_INDEX} sourcePath
    )
    if(AXOLOTY_PACKAGE_NAME STREQUAL "AxolotyWire")
        set(AXOLOTY_WIRE_SOURCE_DIR "${AXOLOTY_PACKAGE_SOURCE}")
    elseif(AXOLOTY_PACKAGE_NAME STREQUAL "AxolotyObjectModel")
        set(AXOLOTY_OBJECT_MODEL_SOURCE_DIR "${AXOLOTY_PACKAGE_SOURCE}")
    elseif(AXOLOTY_PACKAGE_NAME STREQUAL "AxolotyProtocol")
        set(AXOLOTY_PROTOCOL_SOURCE_DIR "${AXOLOTY_PACKAGE_SOURCE}")
    elseif(AXOLOTY_PACKAGE_NAME STREQUAL "AxolotyCoatyModels")
        set(AXOLOTY_COATY_MODELS_SOURCE_DIR "${AXOLOTY_PACKAGE_SOURCE}")
    elseif(AXOLOTY_PACKAGE_NAME STREQUAL "AxolotyStaticRuntime")
        set(AXOLOTY_STATIC_RUNTIME_SOURCE_DIR "${AXOLOTY_PACKAGE_SOURCE}")
    endif()
endforeach()

foreach(AXOLOTY_PACKAGE_SOURCE_DIR IN ITEMS
    AXOLOTY_WIRE_SOURCE_DIR
    AXOLOTY_OBJECT_MODEL_SOURCE_DIR
    AXOLOTY_PROTOCOL_SOURCE_DIR
    AXOLOTY_COATY_MODELS_SOURCE_DIR
    AXOLOTY_STATIC_RUNTIME_SOURCE_DIR
)
    if(NOT DEFINED ${AXOLOTY_PACKAGE_SOURCE_DIR} OR
       NOT IS_DIRECTORY "${${AXOLOTY_PACKAGE_SOURCE_DIR}}")
        message(FATAL_ERROR "preparation report is missing ${AXOLOTY_PACKAGE_SOURCE_DIR}")
    endif()
    file(REAL_PATH "${${AXOLOTY_PACKAGE_SOURCE_DIR}}" AXOLOTY_RESOLVED_PACKAGE_SOURCE)
    if(NOT "${${AXOLOTY_PACKAGE_SOURCE_DIR}}" STREQUAL "${AXOLOTY_RESOLVED_PACKAGE_SOURCE}")
        message(FATAL_ERROR "${AXOLOTY_PACKAGE_SOURCE_DIR} must be canonical")
    endif()
    file(RELATIVE_PATH AXOLOTY_PACKAGE_RELATIVE
        "${AXOLOTY_SOURCE_DIR}" "${AXOLOTY_RESOLVED_PACKAGE_SOURCE}"
    )
    if(IS_ABSOLUTE "${AXOLOTY_PACKAGE_RELATIVE}" OR
       "${AXOLOTY_PACKAGE_RELATIVE}" STREQUAL ".." OR
       "${AXOLOTY_PACKAGE_RELATIVE}" MATCHES "^\.\./")
        message(FATAL_ERROR "${AXOLOTY_PACKAGE_SOURCE_DIR} escapes the Core checkout")
    endif()
endforeach()

string(JSON AXOLOTY_JSON_CORE_SOURCE_DIR GET
    "${AXOLOTY_PREPARATION_JSON}" jsonCore sourceDir
)
string(JSON AXOLOTY_STATIC_RUNTIME_MACRO_TOOL GET
    "${AXOLOTY_PREPARATION_JSON}" staticRuntimeMacro executable
)
string(JSON AXOLOTY_STATIC_RUNTIME_MACRO_SCRATCH_DIR GET
    "${AXOLOTY_PREPARATION_JSON}" staticRuntimeMacro scratchDir
)
foreach(AXOLOTY_SCRATCH_VALUE IN ITEMS
    AXOLOTY_JSON_CORE_SOURCE_DIR
    AXOLOTY_STATIC_RUNTIME_MACRO_SCRATCH_DIR
)
    if(NOT IS_ABSOLUTE "${${AXOLOTY_SCRATCH_VALUE}}" OR
       NOT IS_DIRECTORY "${${AXOLOTY_SCRATCH_VALUE}}")
        message(FATAL_ERROR "${AXOLOTY_SCRATCH_VALUE} from the preparation report is not a directory")
    endif()
    file(REAL_PATH "${${AXOLOTY_SCRATCH_VALUE}}" AXOLOTY_SCRATCH_REAL)
    if(NOT "${${AXOLOTY_SCRATCH_VALUE}}" STREQUAL "${AXOLOTY_SCRATCH_REAL}")
        message(FATAL_ERROR "${AXOLOTY_SCRATCH_VALUE} must be canonical")
    endif()
endforeach()
if(NOT IS_ABSOLUTE "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}" OR
   NOT EXISTS "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}" OR
   NOT IS_EXECUTABLE "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}")
    message(FATAL_ERROR "static-runtime macro executable is missing")
endif()
file(REAL_PATH "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}" AXOLOTY_MACRO_REAL)
if(NOT "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}" STREQUAL "${AXOLOTY_MACRO_REAL}")
    message(FATAL_ERROR "static-runtime macro executable must be canonical")
endif()
file(RELATIVE_PATH AXOLOTY_MACRO_RELATIVE
    "${AXOLOTY_STATIC_RUNTIME_MACRO_SCRATCH_DIR}"
    "${AXOLOTY_STATIC_RUNTIME_MACRO_TOOL}"
)
if(IS_ABSOLUTE "${AXOLOTY_MACRO_RELATIVE}" OR
   "${AXOLOTY_MACRO_RELATIVE}" STREQUAL ".." OR
   "${AXOLOTY_MACRO_RELATIVE}" MATCHES "^\.\./")
    message(FATAL_ERROR "static-runtime macro executable escapes caller scratch")
endif()
